/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package groupsorter;

/**
 *
 * @author niall
 */
public class helpMenu extends javax.swing.JFrame {

    /**
     * Creates new form helpMenu
     */
    public helpMenu() {
        initComponents();
        buttonText.setText("<html>+ Add Student - This button manually adds a student into the system and display their information in the list on the left. <br>"
                + "+ Import students (file) - This button lets the user select either a database or a text file that stores a class of students. These must be formatted in a certain way (see below). <br>"
                + "+ Load saved students - This button loads the class directly from a database within the system itself, there is only one but there is no need for file selection. <br>"
                + "+ Export students (database) - This button lets the user select an external database for the list of students to be stored. <br>"
                + "+ Export students (text file) - This button lets the user select an external text file for the list of students to be stored. <br>"
                + "+ Save loaded students - This button saves the students into the previously mentioned internal database. <br>"
                + "+ Sort - This button sorts the students in the list on the left into different groups, making sure every group has a role with one person in (if possible) and grouping the highest attending students together. <br>"
                + "+ Edit Student - If a student is selected in the list on the left, this button lets the user edit their details. <br>"
                + "+ Help! - I'm sure you already know what this button does. <br>"
                + "+ Exit - Closes the system.</html>");
        formattingText.setText("<html>Text files must be formatting with each student's information on a seperate line. <br>"
                + "The lines must be laid out exactly as follows: <br>"
                + "StudentID,StudentName,PreferredRole,Attendance,GroupNumber, <br>"
                + "If the student is not yet in a group, GroupNumber should be set to -1 <br><br>"
                + "Database files must have a table named 'Students' which has the following 5 columns: studentID, studentName, prefRole, attendance, groupID <br><br>"
                + "Files can be loaded in one format and saved in another </html>");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        exitButton = new javax.swing.JButton();
        helpTitle = new javax.swing.JLabel();
        buttonText = new javax.swing.JLabel();
        buttonTitle = new javax.swing.JLabel();
        formattingTitle = new javax.swing.JLabel();
        formattingText = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        exitButton.setText("Back");
        exitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitButtonMouseClicked(evt);
            }
        });

        helpTitle.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        helpTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        helpTitle.setText("How to use the system");

        buttonText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        buttonText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        buttonText.setText("jLabel2");
        buttonText.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        buttonTitle.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        buttonTitle.setText("Buttons");

        formattingTitle.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        formattingTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        formattingTitle.setText("Formatting");

        formattingText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        formattingText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        formattingText.setText("jLabel2");
        formattingText.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(formattingText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonTitle, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(helpTitle, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE)
                    .addComponent(buttonText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(formattingTitle, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(exitButton)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(helpTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonText, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(formattingTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(formattingText, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(exitButton)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButtonMouseClicked
        this.dispose();
    }//GEN-LAST:event_exitButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(helpMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(helpMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(helpMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(helpMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new helpMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel buttonText;
    private javax.swing.JLabel buttonTitle;
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel formattingText;
    private javax.swing.JLabel formattingTitle;
    private javax.swing.JLabel helpTitle;
    // End of variables declaration//GEN-END:variables
}
